name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  CompatHelper:
    uses: AlgebraicJulia/.github/.github/workflows/julia_compat.yml@main
    secrets: inherit
